mysql:
  host: 127.0.0.1
  port: 3306
  db:  gvb_db
  user: root
  password: 123456
  log_level: dev

logger:
  level: info
  prefix: "[gvb]"  # 前缀
  director: log    # 存放目录
  show_line: true   # 显示行号
  log_in_console: true  # 显示路径

system:
  host: "0.0.0.0"
  port: 8080
  env: dev